/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjpedidos;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import prjpedidos.PedidosView;
import static prjpedidos.PedidosView.itemWindow;
/**
 *
 * @author souza
 */
public class ItemView extends javax.swing.JFrame {
    protected ItemPedido item;
    protected Produto prod;


    public ItemView() {
        initComponents();
        prod= new Produto();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        cbProd = new javax.swing.JComboBox<>();
        lblPro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtQTDD = new javax.swing.JTextField();
        lblTotalitem = new javax.swing.JLabel();
        txtTotalItem = new javax.swing.JTextField();
        cmdAddITEM = new javax.swing.JButton();
        cmdSairItem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Adicionar Itens");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cbProd.setModel(new DefaultComboBoxModel(GerenciarPedidos.listaProduto.toArray())
        );

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cbProd, org.jdesktop.beansbinding.ObjectProperty.create(), cbProd, org.jdesktop.beansbinding.BeanProperty.create("elements"));
        bindingGroup.addBinding(binding);

        cbProd.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbProdItemStateChanged(evt);
            }
        });
        cbProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProdActionPerformed(evt);
            }
        });

        lblPro.setText("Produto");

        jLabel1.setText("Quantidade");

        lblTotalitem.setText("Total");

        txtTotalItem.setEditable(false);

        cmdAddITEM.setText("Adicionar");
        cmdAddITEM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddITEMActionPerformed(evt);
            }
        });

        cmdSairItem.setText("Sair");
        cmdSairItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSairItemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Item");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblPro)
                    .addComponent(cbProd, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalitem)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdAddITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(cmdSairItem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtQTDD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblPro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(txtQTDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(lblTotalitem)
                .addGap(6, 6, 6)
                .addComponent(txtTotalItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAddITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdSairItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProdActionPerformed

         
    }//GEN-LAST:event_cbProdActionPerformed

    private void cmdAddITEMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddITEMActionPerformed
       
        try {
        Produto p = new Produto();
        for (Produto pro : GerenciarPedidos.listaProduto) {
            if (cbProd.getSelectedItem().equals(pro.nome)){
                double r =pro.valor * Integer.parseInt(txtQTDD.getText());
                String tex = String.valueOf(r);
                txtTotalItem.setText(tex);
                if (pro.quantidade>=Integer.parseInt(txtQTDD.getText())){
                pro.quantidade-=Integer.parseInt(txtQTDD.getText());}
                else{
                   throw new SemProd ();    
                }
                p=pro;
            }
        }
        item = new ItemPedido();
        
        item.produto=p;
        item.quantidade=Integer.parseInt(txtQTDD.getText());
        item.valorTotal= Double.parseDouble(txtTotalItem.getText());
        PedidosView.ped.lista.add(item);
        PedidosView.itemWindow.setVisible(false);
        txtQTDD.setText("");
        txtTotalItem.setText("");
        PedidosView.apresentarListaNaTabela();
        //atualiza o total do pedido
        atualizaTotalPedido();
        }catch (NumberFormatException e){
           JOptionPane.showMessageDialog(null, "Os campos devem ser preenchidos");
          
      } catch (SemProd ex) {    
          JOptionPane.showMessageDialog(null, "Erro: " +ex.toString())  ;
        }    
        
    }//GEN-LAST:event_cmdAddITEMActionPerformed

    private String string;

    /**
     * Get the value of string
     *
     * @return the value of string
     */
    public String getString() {
        return string;
    }

    /**
     * Set the value of string
     *
     * @param string new value of string
     */
    public void setString(String string) {
        this.string = string;
    }

    private void atualizaTotalPedido(){
        PedidosView.txtValorTotal.setText("");
        List<ItemPedido> itens = PedidosView.ped.lista;
        double totalItens = 0;
        for(int i = 0; i < itens.size(); i++){
            totalItens += itens.get(i).valorTotal;
        }
        PedidosView.txtValorTotal.setText(String.valueOf(totalItens));
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (Produto pro : GerenciarPedidos.listaProduto) {
            cbProd.addItem(pro.nome);
        }
        
        
    }//GEN-LAST:event_formWindowOpened

    private void cbProdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbProdItemStateChanged

    }//GEN-LAST:event_cbProdItemStateChanged

    private void cmdSairItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSairItemActionPerformed
      itemWindow.setVisible(false);
    }//GEN-LAST:event_cmdSairItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbProd;
    private javax.swing.JButton cmdAddITEM;
    private javax.swing.JButton cmdSairItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblPro;
    private javax.swing.JLabel lblTotalitem;
    private javax.swing.JTextField txtQTDD;
    private javax.swing.JTextField txtTotalItem;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables





}
