/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjpedidos;

/**
 *
 * @author souza
 */
public class MenuView extends javax.swing.JFrame {
    public static PedidosView tela;
    public static ProdutoView telaPro;

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
        tela= new PedidosView();
        telaPro = new ProdutoView();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmdProdutos = new javax.swing.JButton();
        cmdPedidos = new javax.swing.JButton();
        cmdSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmdProdutos.setBackground(new java.awt.Color(153, 117, 136));
        cmdProdutos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdProdutos.setText("PRODUTOS");
        cmdProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdProdutosActionPerformed(evt);
            }
        });

        cmdPedidos.setBackground(new java.awt.Color(162, 102, 165));
        cmdPedidos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdPedidos.setText("PEDIDOS");
        cmdPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdPedidosMouseClicked(evt);
            }
        });
        cmdPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPedidosActionPerformed(evt);
            }
        });

        cmdSair.setBackground(new java.awt.Color(102, 0, 102));
        cmdSair.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmdSair.setForeground(new java.awt.Color(255, 255, 255));
        cmdSair.setText("SAIR");
        cmdSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(213, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmdSair, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addComponent(cmdPedidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE))
                .addGap(172, 172, 172))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(cmdProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(cmdPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(cmdSair, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPedidosActionPerformed
        
    }//GEN-LAST:event_cmdPedidosActionPerformed

    private void cmdPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdPedidosMouseClicked
        tela.setVisible(true);
        
    }//GEN-LAST:event_cmdPedidosMouseClicked

    private void cmdProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdProdutosActionPerformed
        telaPro.setVisible(true);
    }//GEN-LAST:event_cmdProdutosActionPerformed

    private void cmdSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdPedidos;
    private javax.swing.JButton cmdProdutos;
    private javax.swing.JButton cmdSair;
    // End of variables declaration//GEN-END:variables
}
