/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prjpedidos;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import prjpedidos.Pedido;
import prjpedidos.MenuView;

/**
 *
 * @author souza
 */
public class PedidosView extends javax.swing.JFrame {
    public static Pedido ped;
    public static  ItemView itemWindow;
    public static ConsultaPedido consulta;
    /**
     * Creates new form PedidosView
     */
    public PedidosView() {
        initComponents();
        ped=new Pedido();
        itemWindow=new ItemView();
        consulta = new ConsultaPedido();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumPedido = new javax.swing.JLabel();
        txtNumPedido = new javax.swing.JTextField();
        lblDataPedido = new javax.swing.JLabel();
        txtDataPedido = new javax.swing.JTextField();
        lblValorTotal = new javax.swing.JLabel();
        txtValorTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemPedido = new javax.swing.JTable();
        cmdAdicionar = new javax.swing.JButton();
        cmdFecharPedido = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmdConsultar = new javax.swing.JButton();

        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblNumPedido.setText("NÚMERO PEDIDO");

        txtNumPedido.setEditable(false);
        txtNumPedido.setBackground(new java.awt.Color(255, 255, 255));

        lblDataPedido.setText("DATA");

        lblValorTotal.setText("TOTAL");

        txtValorTotal.setDisabledTextColor(new java.awt.Color(0, 153, 153));
        txtValorTotal.setEnabled(false);

        tblItemPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "PRODUTO", "QUANTIDADE", "VALOR TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tblItemPedido);

        cmdAdicionar.setBackground(new java.awt.Color(204, 255, 255));
        cmdAdicionar.setText("Adicionar Item");
        cmdAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdAdicionarMouseClicked(evt);
            }
        });
        cmdAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAdicionarActionPerformed(evt);
            }
        });

        cmdFecharPedido.setBackground(new java.awt.Color(204, 204, 255));
        cmdFecharPedido.setText("Fechar Pedido");
        cmdFecharPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdFecharPedidoMouseClicked(evt);
            }
        });
        cmdFecharPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFecharPedidoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("NOVO PEDIDO");

        jLabel2.setText("ITENS");

        cmdConsultar.setBackground(new java.awt.Color(204, 0, 204));
        cmdConsultar.setText("CONSULTAR PEDIDOS");
        cmdConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdConsultarMouseClicked(evt);
            }
        });
        cmdConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNumPedido)
                                .addGap(146, 146, 146)
                                .addComponent(lblDataPedido)
                                .addGap(163, 163, 163)
                                .addComponent(lblValorTotal))
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(txtNumPedido)
                            .addComponent(cmdAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmdFecharPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdConsultar)
                                .addGap(91, 91, 91))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(cmdConsultar)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumPedido)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataPedido)
                            .addComponent(lblValorTotal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdFecharPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdAdicionarActionPerformed

    private void cmdConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdConsultarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdConsultarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MenuView.tela.setVisible(false);
        limparTudo();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        MenuView.tela.setVisible(false);
        limparTudo();
    }//GEN-LAST:event_formWindowClosed

    private void cmdFecharPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdFecharPedidoMouseClicked
        
    }//GEN-LAST:event_cmdFecharPedidoMouseClicked

    private void cmdFecharPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFecharPedidoActionPerformed
        
       
        Pedido pedido = new Pedido();
        pedido.data=txtDataPedido.getText();
        pedido.valorTotal=Double.parseDouble(txtValorTotal.getText());
        pedido.numPedido= Integer.parseInt(txtNumPedido.getText());
        pedido.lista=ped.lista;
        GerenciarPedidos.listaPedidos.add(pedido);
        List<Pedido> p = GerenciarPedidos.listaPedidos;
        limparTudo();
        txtNumPedido.setText(String.valueOf(ped.gerarNumeroPedido())); 
        ped.lista = new ArrayList<>();
        apresentarListaNaTabela();
        
    }//GEN-LAST:event_cmdFecharPedidoActionPerformed

    private void cmdAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdAdicionarMouseClicked
        itemWindow.setVisible(true);

    }//GEN-LAST:event_cmdAdicionarMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       txtNumPedido.setText(String.valueOf(Pedido.numInicial));
    }//GEN-LAST:event_formWindowOpened

    private void cmdConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConsultarActionPerformed
       consulta.setVisible(true);
       ConsultaPedido.apresentarListaNaTabela();
    }//GEN-LAST:event_cmdConsultarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        txtNumPedido.setText(String.valueOf(Pedido.numInicial));
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAdicionar;
    private javax.swing.JButton cmdConsultar;
    private javax.swing.JButton cmdFecharPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDataPedido;
    private javax.swing.JLabel lblNumPedido;
    private javax.swing.JLabel lblValorTotal;
    private static javax.swing.JTable tblItemPedido;
    private javax.swing.JTextField txtDataPedido;
    private javax.swing.JTextField txtNumPedido;
    public static javax.swing.JTextField txtValorTotal;
    // End of variables declaration//GEN-END:variables
static void apresentarListaNaTabela() {
        
        DefaultTableModel modelo = (DefaultTableModel) tblItemPedido.getModel();
        modelo.setNumRows(0);
        for (ItemPedido item: ped.lista ) {        
    
            modelo.addRow(new Object[]{
                item.produto.nome,
                item.quantidade,
                item.valorTotal
            });
        }
    }

    private void limparTudo() {
        for (Component item : this.getContentPane().getComponents()) {
            if(item instanceof JTextField){
                
                JTextField obj = (JTextField) item;
                //JOptionPane.showMessageDialog(null, obj.getName());
               if(!"id".equals(obj.getName()))  obj.setText(null);
            }
        }
    }



}
